formatter: markdown
sections:
  show:
    - inputs
    - outputs
    - providers
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
sort:
  enabled: true
  by: required
settings:
  indent: 4
  escape: false
  default: true
  required: true
  type: true
  lockfile: false
  hide-empty: true
